# Title xyz
TITLE_Y = 45
TITLE_FONT_SIZE = 16
# Fade timing
# Values are frames at 60FPS
TITLE_FADE_IN_FRAMES = 90
TITLE_WHITE_HOLD_FRAMES = 258
TITLE_FADE_OUT_FRAMES = 90
TITLE_LOOP_RESET = True
# left hud
LEFT_HUD_X = 40
LEFT_HUD_Y_OFFSET = 60
LEFT_HUD_SPACING = 24
# right hud
RIGHT_HUD_OFFSET_X = 170
RIGHT_HUD_OFFSET_Y = 80
RIGHT_HUD_SPACING = 24
# font sizes
HUD_FONT_SIZE = 9
TITLE_FONT = "Segoe UI"
HUD_FONT = "Consolas"
# hud colours
HUD_RED = 180
HUD_GREEN = 230
HUD_BLUE = 255
